### PR TITLE
corrected shifTowards and changed angle

### PR DESCRIPTION
**Pull request by QuentinFelix**
angle should give the same results
shiftTowards always takes the absolute value

### CODE REVIEW

**Comment by joostdecock** [comment]
As I explained on Gitter, I can not merge this pull request because it's a rewrite of the original angle code that was incorrect.

But, I would have not realised that if it wasn't for this PR, so this was extremely valuable. Thank you for submitting it!

**Comment by QuentinFelix** [comment]
Is that bad for my stats?

**Comment by joostdecock** [comment]
Stats are not very indicative of contribution.

If you want good stats, you check out the repository, run a tool on it that strips whitespace and does other auto-formatting of code, and submit it.
That way, it looks like you have touched almost every line of code in the repository, but your contribution is actually nothing.

Some people [do that, and nothing else](https://github.com/freesewing/core/commit/08007d89cbf14bbee3f1f841db4370dd41ddc0a4). Don't be like those people ;)

**Comment by QuentinFelix** [comment]
Haha that's a lot of colors for not much.
It could be a way to hide easter egg comments among all the spaces removed... Did you review each changes?

But you can't break others patterns drafts SA with that kind of PR =P

**Comment by joostdecock** [comment]
It was december 2016, so nothing really worked back then. Easter eggs was the least of my worries ;)

**Pull request closed without merging**
