### PR TITLE
Added 'extrasmall' mode to part::addTitle()

### PR DESCRIPTION
**Pull request by woutervdub**

### CODE REVIEW

**Comment by joostdecock** [comment]
I've got two questions about this pull request:

- You've changed the default setting to include an extra top button in the simon config file. Was this a mistake, or do you intended that change. If so, why?
- This does address the button free length being off by 2cm as reported in [issue 112 in the site repo](https://github.com/freesewing/site/issues/112) but does not seem to address the second complaint in that ticket about the topmost button being too low. Is that correct?

**Comment by woutervdub** [comment]
The change to SimonShirt does two things:
- fix the placement of the bottom-most button to align with the waist.
- place all buttons with an equal distance *including the collar button*.

This moves the top button up because the button is no longer placed at a distance from the top of the front part, but at that distance from the button on the collarband. 

Because this moves the top button up, I changed the default for the extra button option to *off*.

**Comment by joostdecock** [comment]
The original comment in the issue reported by @Stefan1960 is that the distance from the top button to the collar button should be less than the distance between other buttons. Which is true, but that's why we have the extra top button option.

Now, for those who do not want and extra top button, the highest front button is indeed too low and I think that's what @Stefan1960 is reporting.

Now apart from that, and on a more technical note, this pull request is against the master branch. That's not ok ;)

You should always create your own branch and then submit your pull requests to the *develop* branch. This way, all changes are merged into develop (yours mine, etc) which is where a new core release is prepared.

If we merge into master (and I could have easily pushed the merge button if I wasn't paying attention) that will trigger an automatic deploy and that code would be live.

That's not how we release new code into production. We prepare everything, update the changelog to include info on the new release. Then merge into master, and create a new release that will become available on packagist.

Sorry if this is confusing but it boils down to this: Your pull requests should always go to develop.


I'm going to close this one, because I can't merge it into master. However, I will port your code into the develop branch so I can merge it into master later when preparing a new release. (which I hope to do today).

I'll make sure to mention this in Gitter too because it's important for collaborators to understand.

**Comment by woutervdub** [comment]
I read up on placements of the top button versus distance between buttons across shirts. What I found was that there are set distances between buttons and the one at the top. Some houses that make custom shirts allow you to move the top button up or down by a half or a whole inch.  

But that cannot be combined with the option of providing as many or little buttons on the shirt as you want. So I looked at your documentation of the shirt and figured that the pattern should follow what the description and graphics showed. It shows equal distance for all buttons, including the collarband one.

We can make an extra setting to move the top button up or down, but that would make the extra button option redundant, I guess.

**Comment by woutervdub** [comment]
I'm sorry I messed up the normal flow of code changes. I did not mean to change things in the master. I just tried to follow the steps you outlined in gitter to get my changes back in. Does this mean I have a clone of the master branch and not the development branch? How can I tell? And how can I switch?

**Comment by joostdecock** [comment]
No worries. Things can get confusing sometimes. Happens to me all the time :)

To know where you are: `git status`
To swith to a branch of your choice: `git checkout -b develop`
(obviously develop can be any other name, including a non-existing branch in which case that branch will be created)

**Pull request closed without merging**
